// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _2026_Roomify_Backend.Data;

#nullable disable

namespace _2026_Roomify_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211155626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_2026_Roomify_Backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasColumnName("building_id");

                    b.Property<string>("JamMulai")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jam_mulai");

                    b.Property<string>("JamSelesai")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jam_selesai");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keperluan");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_peminjam");

                    b.Property<string>("NoKontak")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("no_kontak");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("_2026_Roomify_Backend.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama");

                    b.HasKey("Id");

                    b.ToTable("buildings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "Gedung D4"
                        },
                        new
                        {
                            Id = 2,
                            Nama = "Gedung D3"
                        },
                        new
                        {
                            Id = 3,
                            Nama = "Gedung SAW"
                        },
                        new
                        {
                            Id = 4,
                            Nama = "Gedung Pasca"
                        });
                });

            modelBuilder.Entity("_2026_Roomify_Backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasColumnName("buildingid");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("integer")
                        .HasColumnName("kapasitas");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipe");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Kapasitas = 30,
                            Nama = "R.101",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            Kapasitas = 20,
                            Nama = "R.102",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 1,
                            Kapasitas = 20,
                            Nama = "R.103",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 1,
                            Kapasitas = 20,
                            Nama = "R.104",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 1,
                            Kapasitas = 20,
                            Nama = "Lab.IT",
                            Status = "kosong",
                            Tipe = "Laboratorium"
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = 2,
                            Kapasitas = 20,
                            Nama = "R.201",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = 2,
                            Kapasitas = 25,
                            Nama = "R.202",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 8,
                            BuildingId = 2,
                            Kapasitas = 15,
                            Nama = "Lab IoT",
                            Status = "kosong",
                            Tipe = "Laboratorium"
                        },
                        new
                        {
                            Id = 9,
                            BuildingId = 2,
                            Kapasitas = 30,
                            Nama = "R.203",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 10,
                            BuildingId = 3,
                            Kapasitas = 40,
                            Nama = "Ruang 301",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 11,
                            BuildingId = 3,
                            Kapasitas = 35,
                            Nama = "Ruang 302",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 12,
                            BuildingId = 3,
                            Kapasitas = 20,
                            Nama = "Lab Multimedia",
                            Status = "kosong",
                            Tipe = "Laboratorium"
                        },
                        new
                        {
                            Id = 13,
                            BuildingId = 4,
                            Kapasitas = 25,
                            Nama = "Ruang 401",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 14,
                            BuildingId = 4,
                            Kapasitas = 25,
                            Nama = "Ruang 402",
                            Status = "kosong",
                            Tipe = "Kelas"
                        },
                        new
                        {
                            Id = 15,
                            BuildingId = 4,
                            Kapasitas = 15,
                            Nama = "Lab Research",
                            Status = "kosong",
                            Tipe = "Laboratorium"
                        });
                });

            modelBuilder.Entity("_2026_Roomify_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "password123",
                            Role = "User",
                            Username = "zahrin"
                        });
                });

            modelBuilder.Entity("_2026_Roomify_Backend.Models.Booking", b =>
                {
                    b.HasOne("_2026_Roomify_Backend.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_Roomify_Backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_Roomify_Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2026_Roomify_Backend.Models.Room", b =>
                {
                    b.HasOne("_2026_Roomify_Backend.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("_2026_Roomify_Backend.Models.Building", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
